name: Deploy

on: [push]
jobs:
deploy:
runs-on: ubuntu-latest
steps:
    - uses: actions/checkout@v3
    - run: |
          set -eu
          mkdir "$HOME/.ssh"
          echo "${{secrets.KEY}}" > "$HOME/.ssh/key"
          chmod 600 "$HOME/.ssh/key"
          npm ci
          npm run build
          cd dist
          rsync -e "ssh -p 20022 -i $HOME/.ssh/key -o StrictHostKeyChecking=no" --archive --compress --delete . u1801466@31.31.198.36:/var/www/u1801466/data/www/gromka.tech/test