name: Deploy

on: [push]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: |
                  set -eu
                  mkdir "$HOME/.ssh"
                  echo "${{secrets.REGRU}}" > "$HOME/.ssh/regru"
                  chmod 600 "$HOME/.ssh/regru"
                  npm ci
                  npm run build
                  cd dist
                  rsync -e "ssh -i $HOME/.ssh/regru -o StrictHostKeyChecking=no" --archive --compress --delete . u1801466@server242.hosting.reg.ru:/var/www/u1801466/data/www/gromka.tech/test